- apps/programs/workspace.coffee
> [RFR] Python: better main.py template

- apps/programs/api-routes/projects.js
- apps/programs/project.js
- package.json
fixes #42 
I switched to ``archiver``, which can handle asynchronous packing of files (as opposed to zip-stream).  This dependency replaces ``zip-stream`` and ``tar-stream``.
> [RFR] Switching to archiver to fix multi-file zip downloads

- apps/compiler/api-routes/compile.js
- apps/fs/directory.js
- apps/kiss/manifest.json
- apps/kiss/resources/index.jade
- apps/kiss/resources/kiss-view-controller.js
- apps/programs/api-routes/projects.js
- apps/programs/project.js
- apps/programs/workspace.js
- apps/runner/exec.js
- apps/runner/resources/index.jade
- apps/runner/resources/program-service.js
- apps/runner/resources/runner-view-controller.js
- package.json
- server.js
- shared/client/css/style.css
- shared/client/scripts/filename-modal-factory-service.js
- shared/client/scripts/fileread-directive.js
- shared/client/scripts/harrogate-index-app.js
- shared/client/views/filename-modal.jade
- shared/scripts/user-manager.js
Not for merging... this is for testing both PRs together.
> [RFR] #44 and #45

- apps/programs/workspace.js
Adding a line between #include and main()
> [RFR] Fixing C project template whitespace

- apps/kiss/resources/kiss-view-controller.js
- shared/client/css/style.css
> [RFR] Making syntax highlighting more consistent with previous KISS IDE

- apps/programs/workspace.js
> [RFR] Adding a new line in starting python code

- shared/client/views/templates/app-view-layout.jade
Next we need a help page for the help button.
> [RFR] Javascript home buttons

- apps/kiss/resources/kiss-view-controller.js
> [RFR] Fix Issue #16

- apps/kiss/resources/kiss-view-controller.js
- apps/runner/resources/runner-view-controller.js
In KISS and Runner apps, keeping "Default User" at the top of the list.
> [RFR] Sort users based on name

- apps/kiss/resources/kiss-view-controller.js
- apps/runner/resources/runner-view-controller.js
> [RFR] Sorting projects in the Project Explorer by name

- apps/kiss/resources/index.jade
- apps/kiss/resources/kiss-view-controller.js
The user can click a "minus" button to delete a file.   They are presented with a confirmation modal that displays the filename for the file being deleted.
The spacing seems a little weird, there is probably a better way to do this than with ``&nbsp;&nbsp;``
> [RFR] Delete files from the Project  xplorer

- apps/kiss/resources/index.jade
- apps/kiss/resources/kiss-view-controller.js
- apps/programs/api-routes/projects.js
- apps/programs/workspace.js
- apps/settings/api-routes/workspace.js
- apps/settings/exec.js
- apps/settings/manifest.json
- apps/settings/resources/index.jade
- apps/settings/resources/settings-view-controller.js
- apps/user/resources/index.jade
- apps/user/resources/users-view-controller.js
- shared/client/scripts/harrogate-index-app.js
- shared/client/scripts/workspace-manager-service.js
- shared/scripts/user-manager.js
- shared/scripts/workspace-manager.js
@bmcdorman and I are adding a user preference selection to simplify the interface... which should be a UX improvement for most users.
> [RFR] User preferences (simple/advanced mode)

- apps/kiss/resources/index.jade
- apps/kiss/resources/kiss-view-controller.js
- apps/runner/resources/runner-view-controller.js
Now the user won't need to leave the page with their code to start the program.
> [RFR] Showing runner from KISS app

- shared/client/scripts/harrogate-index-app.js
We started a new 10 Hz timer every time the index app was loaded (like when switching between home and the KISS IDE)
> [RFR] Fixing spam of link status check

- apps/user/resources/users-view-controller.js
> [RFR] Fixing saving of user preferences 

- apps/kiss/resources/kiss-view-controller.js
Making our auto-indent consistent with how we are teaching and the code templates.
> [RFR] Four space indentation in KISS

- apps/kiss/resources/index.jade
- apps/kiss/resources/kiss-view-controller.js
...also disable the compile button during program execution.
> [RFR] Dont allow run during compilation

- package-lock.json
- package.json
- shared/scripts/settings-manager.js
- shared/scripts/user-manager.js
- shared/scripts/workspace-manager.js
The new version of writeFile requires a callback.
https://nodejs.org/api/fs.html#fs_fs_writefile_file_data_options_callback
> fix: added callback

- apps/programs/workspace.js
Removed motor and msleep from starting python code to be consistent with curriculum.
> Remove motor and msleep

- package-lock.json
- package.json
Fixed: https://github.com/kipr/harrogate/issues/105
> Reverted changes made in 626daa9 and 2c52b6a

- shared/scripts/user-manager.js
- shared/scripts/workspace-manager.js
Fixed issue of path's pointing to root instead of /home/kipr. Added TODO for automatic /var/local/KIPR Software Suite directory creation. Made not in build steps for Wombat.
> Fix app data paths
